In [ ]:
import pandas as pd
df = pd.read_csv("student_performance_dataset.csv")
df.head()

,student_id,age,gender,city_type,study_hours_per_day,deep_work_sessions,assignment_completion_rate,attendance_percentage,social_media_hours,doomscrolling_before_sleep,...,family_support,financial_stress,learning_style,career_goal,productivity_after_midnight,revision_efficiency,burnout_risk,consistency_score,final_exam_score,performance_category
0,0,21,Female,Semi-Urban,3.2,7,100,70,3.8,0,...,10,6,Audio,Engineering,9,1,10,3,32,Low
1,1,19,Female,Semi-Urban,3.9,2,46,70,2.6,1,...,2,6,Practical,Business,6,10,4,6,59,Medium
2,2,16,Female,Urban,4.3,7,54,57,4.3,1,...,1,9,Visual,Engineering,7,9,8,1,34,Low
3,3,19,Male,Semi-Urban,5.3,1,78,90,1.7,0,...,5,10,Reading,Medical,7,7,9,10,60,Medium
4,4,17,Female,Urban,4.1,3,100,81,2.6,0,...,5,6,Visual,Medical,4,10,7,9,77,High

In [ ]:
numerical_cols = df.select_dtypes(include=['number']).columns.tolist()
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

print("Numerical columns:", numerical_cols)
print("Categorical columns:", categorical_cols)

Numerical columns: ['student_id', 'age', 'study_hours_per_day', 'deep_work_sessions', 'assignment_completion_rate', 'attendance_percentage', 'social_media_hours', 'doomscrolling_before_sleep', 'notification_distractions', 'ai_tool_usage_hours', 'gaming_hours', 'stress_level', 'motivation_level', 'focus_score', 'procrastination_index', 'sleep_hours', 'caffeine_intake', 'physical_activity_hours', 'internet_quality', 'family_support', 'financial_stress', 'productivity_after_midnight', 'revision_efficiency', 'burnout_risk', 'consistency_score', 'final_exam_score']
Categorical columns: ['gender', 'city_type', 'mental_state', 'learning_style', 'career_goal', 'performance_category']

In [ ]:
print(df.isnull().sum())

student_id                      0
age                             0
gender                          0
city_type                       0
study_hours_per_day             0
deep_work_sessions              0
assignment_completion_rate      0
attendance_percentage           0
social_media_hours             60
doomscrolling_before_sleep      0
notification_distractions       0
ai_tool_usage_hours             0
gaming_hours                    0
stress_level                    0
motivation_level                0
focus_score                    60
procrastination_index           0
mental_state                    0
sleep_hours                    60
caffeine_intake                 0
physical_activity_hours         0
internet_quality                0
family_support                  0
financial_stress                0
learning_style                  0
career_goal                     0
productivity_after_midnight     0
revision_efficiency             0
burnout_risk                    0
consistency_score               0
final_exam_score                0
performance_category            0
dtype: int64

In [ ]:
for col in numerical_cols:
    df[col].fillna(df[col].median(), inplace=True)

for col in categorical_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

print("Total missing values remaining:", df.isnull().sum().sum())

Total missing values remaining: 0

/tmp/ipykernel_4691/2299844341.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
/tmp/ipykernel_4691/2299844341.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

df.head()

,student_id,age,gender,city_type,study_hours_per_day,deep_work_sessions,assignment_completion_rate,attendance_percentage,social_media_hours,doomscrolling_before_sleep,...,family_support,financial_stress,learning_style,career_goal,productivity_after_midnight,revision_efficiency,burnout_risk,consistency_score,final_exam_score,performance_category
0,0,21,0,1,3.2,7,100,70,3.8,0,...,10,6,0,2,9,1,10,3,32,1
1,1,19,0,1,3.9,2,46,70,2.6,1,...,2,6,1,1,6,10,4,6,59,2
2,2,16,0,2,4.3,7,54,57,4.3,1,...,1,9,3,2,7,9,8,1,34,1
3,3,19,1,1,5.3,1,78,90,1.7,0,...,5,10,2,3,7,7,9,10,60,2
4,4,17,0,2,4.1,3,100,81,2.6,0,...,5,6,3,3,4,10,7,9,77,0

In [ ]:
X = df.drop(columns=['performance_category'])
y = df['performance_category']

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (3000, 31)
Shape of y: (3000,)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

X_train shape: (2400, 31)
X_test shape: (600, 31)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("Min value in X_train:", X_train.min())
print("Max value in X_train:", X_train.max())

Min value in X_train: 0.0
Max value in X_train: 1.0

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0

In [ ]:
import pandas as pd

feature_importance = pd.Series(
    model.feature_importances_,
    index=df.drop(columns=['performance_category']).columns
).sort_values(ascending=False)

print(feature_importance)

final_exam_score               1.0
age                            0.0
student_id                     0.0
city_type                      0.0
study_hours_per_day            0.0
deep_work_sessions             0.0
gender                         0.0
attendance_percentage          0.0
social_media_hours             0.0
doomscrolling_before_sleep     0.0
notification_distractions      0.0
ai_tool_usage_hours            0.0
gaming_hours                   0.0
stress_level                   0.0
assignment_completion_rate     0.0
motivation_level               0.0
focus_score                    0.0
mental_state                   0.0
procrastination_index          0.0
caffeine_intake                0.0
physical_activity_hours        0.0
internet_quality               0.0
sleep_hours                    0.0
family_support                 0.0
financial_stress               0.0
career_goal                    0.0
learning_style                 0.0
productivity_after_midnight    0.0
revision_efficiency            0.0
burnout_risk                   0.0
consistency_score              0.0
dtype: float64